stages:
  - build
  - push
  - deploy


build:
  stage: build
  only:
    - master
  tags:
    - api-gw
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo SMS_SENDER_NUMBER=$SMS_SENDER_NUMBER >> .env
    - echo SMS_API_TOKEN=$SMS_API_TOKEN >> .env
    - echo SMS_TEMPLATE=$SMS_TEMPLATE >> .env
    - echo MONGO_HOST=$MONGO_HOST >> .env
    - echo MONGO_PORT=$MONGO_PORT >> .env
    - echo MONGO_USER=$MONGO_USER >> .env
    - echo MONGO_PASS=$MONGO_PASS >> .env
    - echo ATTRIBUTE_MONGO_HOST=$ATTRIBUTE_MONGO_HOST >> .env
    - echo ATTRIBUTE_MONGO_PASS=$ATTRIBUTE_MONGO_PASS >> .env
    - echo ATTRIBUTE_MONGO_PORT=$ATTRIBUTE_MONGO_PORT >> .env
    - echo ATTRIBUTE_MONGO_USER=$ATTRIBUTE_MONGO_USER >> .env
    - echo OLD_MONGO_USER=$OLD_MONGO_USER >> .env
    - echo OLD_MONGO_PASS=$OLD_MONGO_PASS >> .env
    - echo OLD_MONGO_HOST=$OLD_MONGO_HOST >> .env
    - echo OLD_MONGO_PORT=$OLD_MONGO_PORT >> .env
    - echo REDIS_HOST=$REDIS_HOST >> .env
    - echo REDIS_PORT=$REDIS_PORT >> .env
    - echo REDIS_USER=$REDIS_USER >> .env
    - echo REDIS_PASS=$REDIS_PASS >> .env
    - echo REDIS_DB=$REDIS_DB >> .env
    - echo RABBIT_HOST=$RABBIT_HOST >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
    - docker login nexus.aasood.com -u registry -p $REGPASS 
    - docker build -t customer:0.0.1 .

dev_deploy:
  stage: deploy
  only:
    - master
  tags:
    - api-gw
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo SMS_SENDER_NUMBER=$SMS_SENDER_NUMBER >> .env
    - echo SMS_API_TOKEN=$SMS_API_TOKEN >> .env
    - echo SMS_TEMPLATE=$SMS_TEMPLATE >> .env
    - echo MONGO_HOST=$MONGO_HOST >> .env
    - echo MONGO_PORT=$MONGO_PORT >> .env
    - echo MONGO_USER=$MONGO_USER >> .env
    - echo MONGO_PASS=$MONGO_PASS >> .env
    - echo ATTRIBUTE_MONGO_HOST=$ATTRIBUTE_MONGO_HOST >> .env
    - echo ATTRIBUTE_MONGO_PASS=$ATTRIBUTE_MONGO_PASS >> .env
    - echo ATTRIBUTE_MONGO_PORT=$ATTRIBUTE_MONGO_PORT >> .env
    - echo ATTRIBUTE_MONGO_USER=$ATTRIBUTE_MONGO_USER >> .env
    - echo OLD_MONGO_USER=$OLD_MONGO_USER >> .env
    - echo OLD_MONGO_PASS=$OLD_MONGO_PASS >> .env
    - echo OLD_MONGO_HOST=$OLD_MONGO_HOST >> .env
    - echo OLD_MONGO_PORT=$OLD_MONGO_PORT >> .env
    - echo REDIS_HOST=$REDIS_HOST >> .env
    - echo REDIS_PORT=$REDIS_PORT >> .env
    - echo REDIS_USER=$REDIS_USER >> .env
    - echo REDIS_PASS=$REDIS_PASS >> .env
    - echo REDIS_DB=$REDIS_DB >> .env
    - echo RABBIT_HOST=$RABBIT_HOST >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker-compose -f docker-compose.yaml up -d --build

push:
  stage: push
  only:
    - dev
  tags:
    - deploy
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo SMS_SENDER_NUMBER=$SMS_SENDER_NUMBER >> .env
    - echo SMS_API_TOKEN=$SMS_API_TOKEN >> .env
    - echo SMS_TEMPLATE=$SMS_TEMPLATE >> .env
    - echo MONGO_HOST="172.16.16.16" >> .env
    - echo MONGO_PORT=$MONGO_PORT >> .env
    - echo MONGO_USER=$MONGO_USER >> .env
    - echo MONGO_PASS=$MONGO_PASS >> .env
    - echo ATTRIBUTE_MONGO_HOST="172.16.16.16" >> .env
    - echo ATTRIBUTE_MONGO_PASS=$ATTRIBUTE_MONGO_PASS >> .env
    - echo ATTRIBUTE_MONGO_PORT=$ATTRIBUTE_MONGO_PORT >> .env
    - echo ATTRIBUTE_MONGO_USER=$ATTRIBUTE_MONGO_USER >> .env
    - echo OLD_MONGO_USER=$OLD_MONGO_USER >> .env
    - echo OLD_MONGO_PASS=$OLD_MONGO_PASS >> .env
    - echo OLD_MONGO_HOST=$OLD_MONGO_HOST >> .env
    - echo OLD_MONGO_PORT=$OLD_MONGO_PORT >> .env
    - echo REDIS_HOST="172.16.16.16" >> .env
    - echo REDIS_PORT=$REDIS_PORT >> .env
    - echo REDIS_USER=$REDIS_USER >> .env
    - echo REDIS_PASS=$REDIS_PASS >> .env
    - echo REDIS_DB=$REDIS_DB >> .env
    - echo RABBIT_HOST="172.16.16.16" >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker build -t customer:0.0.1 .# -t nexus.aasood.com/backend/customer:$CI_COMMIT_SHORT_SHA
#    - docker push nexus.aasood.com/backend/customer:$CI_COMMIT_SHORT_SHA

master_deploy:
  stage: deploy
  only:
    - dev
  tags:
    - deploy
  script:
    - echo APP_NAME=$APP_NAME >> .env
    - echo SMS_SENDER_NUMBER=$SMS_SENDER_NUMBER >> .env
    - echo SMS_API_TOKEN=$SMS_API_TOKEN >> .env
    - echo SMS_TEMPLATE=$SMS_TEMPLATE >> .env
    - echo MONGO_HOST="172.16.16.16" >> .env
    - echo MONGO_PORT=$MONGO_PORT >> .env
    - echo MONGO_USER=$MONGO_USER >> .env
    - echo MONGO_PASS=$MONGO_PASS >> .env
    - echo ATTRIBUTE_MONGO_HOST="172.16.16.16" >> .env
    - echo ATTRIBUTE_MONGO_PASS=$ATTRIBUTE_MONGO_PASS >> .env
    - echo ATTRIBUTE_MONGO_PORT=$ATTRIBUTE_MONGO_PORT >> .env
    - echo ATTRIBUTE_MONGO_USER=$ATTRIBUTE_MONGO_USER >> .env
    - echo OLD_MONGO_USER=$OLD_MONGO_USER >> .env
    - echo OLD_MONGO_PASS=$OLD_MONGO_PASS >> .env
    - echo OLD_MONGO_HOST=$OLD_MONGO_HOST >> .env
    - echo OLD_MONGO_PORT=$OLD_MONGO_PORT >> .env
    - echo REDIS_HOST="172.16.16.16" >> .env
    - echo REDIS_PORT=$REDIS_PORT >> .env
    - echo REDIS_USER=$REDIS_USER >> .env
    - echo REDIS_PASS=$REDIS_PASS >> .env
    - echo REDIS_DB=$REDIS_DB >> .env
    - echo RABBIT_HOST="172.16.16.16" >> .env
    - echo RABBIT_PORT=$RABBIT_PORT >> .env
    - echo RABBIT_USER=$RABBIT_USER >> .env
    - echo RABBIT_PASS=$RABBIT_PASS >> .env
#    - docker login nexus.aasood.com -u registry -p $REGPASS
    - docker-compose -f docker-compose.yaml up -d --build
